/*
===============================================================================
DDL Script: Create Silver Tables
===============================================================================
Script Purpose:
    This script creates tables in the 'silver' schema based on incomin data from bronze tables, 
    dropping existing tables if they already exist.
	  Run this script to re-define the DDL structure of 'silver' Tables.
===============================================================================
*/
IF OBJECT_ID('SILVER.CRM_CUST_INFO','U') IS NOT NULL DROP TABLE SILVER.CRM_CUST_INFO;
GO
CREATE TABLE SILVER.CRM_CUST_INFO
(
	CST_ID	INT,
	CST_KEY	NVARCHAR(30),
	CST_FIRSTNAME NVARCHAR(30),
	CST_LASTNAME NVARCHAR(30),	
	CST_MARITAL_STATUS NVARCHAR(5),	
	CST_GENDER NVARCHAR(5),	
	CST_CREATE_DATE DATE,
	DWH_CREATE_DATE DATETIME DEFAULT GETDATE()
);
GO
IF OBJECT_ID('SILVER.CRM_PRD_INFO','U') IS NOT NULL DROP TABLE SILVER.CRM_PRD_INFO;
GO
CREATE TABLE SILVER.CRM_PRD_INFO
(PRD_ID INT,
CAT_ID NVARCHAR(10),
PRD_KEY NVARCHAR(30),	
PRD_NM NVARCHAR(60),	
PRD_COST INT,
PRD_LINE NVARCHAR(5),	
PRD_START_DT DATE,	
PRD_END_DT DATE,
DWH_CREATE_DATE DATETIME DEFAULT GETDATE()
);
GO
IF OBJECT_ID('SILVER.CRM_SALES_DETAILS','U') IS NOT NULL DROP TABLE SILVER.CRM_SALES_DETAILS;
GO
CREATE TABLE SILVER.CRM_SALES_DETAILS
(
SLS_ORD_NUM NVARCHAR(20),
SLS_PRD_KEY	NVARCHAR(20),
SLS_CUST_ID	INT,
SLS_ORDER_DT DATE,
SLS_SHIP_DT	DATE,
SLS_DUE_DT DATE,	
SLS_SALES INT,	
SLS_QUANTITY INT,	
SLS_PRICE INT,
DWH_CREATE_DATE DATETIME DEFAULT GETDATE()
);
GO
IF OBJECT_ID('SILVER.ERP_CUST_AZ12','U') IS NOT NULL DROP TABLE SILVER.ERP_CUST_AZ12;
GO
CREATE TABLE SILVER.ERP_CUST_AZ12
(CID NVARCHAR(20),
BDATE DATE,
GEN NVARCHAR(10),
DWH_CREATE_DATE DATETIME DEFAULT GETDATE()
);
GO
IF OBJECT_ID('SILVER.ERP_LOC_A101','U') IS NOT NULL DROP TABLE SILVER.ERP_LOC_A101;
GO
CREATE TABLE SILVER.ERP_LOC_A101
(CID NVARCHAR(50),
CNTRY NVARCHAR(50)
);
GO
IF OBJECT_ID('SILVER.ERP_PX_CAT_G1V2','U') IS NOT NULL DROP TABLE SILVER.ERP_PX_CAT_G1V2;
GO
CREATE TABLE SILVER.ERP_PX_CAT_G1V2
(ID NVARCHAR(10),
CAT NVARCHAR(20),
SUBCAT NVARCHAR(30),
MAINTENANCE NVARCHAR(5),
DWH_CREATE_DATE DATETIME DEFAULT GETDATE()
);

